-- begin TEST3_ORDER
alter table TEST3_ORDER add constraint FK_TEST3_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references TEST3_CUSTOMER(ID)^
create index IDX_TEST3_ORDER_ON_CUSTOMER on TEST3_ORDER (CUSTOMER_ID)^
-- end TEST3_ORDER
-- begin TEST3_ORDER_LINE
alter table TEST3_ORDER_LINE add constraint FK_TEST3_ORDER_LINE_ON_ORDER foreign key (ORDER_ID) references TEST3_ORDER(ID)^
alter table TEST3_ORDER_LINE add constraint FK_TEST3_ORDER_LINE_ON_PRODUCT foreign key (PRODUCT_ID) references TEST3_PRODUCT(ID)^
create index IDX_TEST3_ORDER_LINE_ON_ORDER on TEST3_ORDER_LINE (ORDER_ID)^
create index IDX_TEST3_ORDER_LINE_ON_PRODUCT on TEST3_ORDER_LINE (PRODUCT_ID)^
-- end TEST3_ORDER_LINE
