alter table TEST3_ORDER_LINE add constraint FK_TEST3_ORDER_LINE_ON_ORDER foreign key (ORDER_ID) references TEST3_ORDER(ID);
alter table TEST3_ORDER_LINE add constraint FK_TEST3_ORDER_LINE_ON_PRODUCT foreign key (PRODUCT_ID) references TEST3_PRODUCT(ID);
create index IDX_TEST3_ORDER_LINE_ON_ORDER on TEST3_ORDER_LINE (ORDER_ID);
create index IDX_TEST3_ORDER_LINE_ON_PRODUCT on TEST3_ORDER_LINE (PRODUCT_ID);
